defaultTasks 'clean', 'build'

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'eclipse'

version = '1.0-SNAPSHOT'
group = 'org.suggs.interviews.berlinclock'

wrapper {
    description = 'Generates gradlew scripts for NIX and win envs'
    gradleVersion = '7.3'
}

repositories {
    mavenCentral()
}

idea.module {
    downloadSources = true
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.5',
            'commons-lang:commons-lang:2.6'

    implementation 'org.slf4j:slf4j-log4j12:1.7.5',
            'log4j:log4j:1.2.17'

    testImplementation 'org.mockito:mockito-core:5.15.2',
            'org.assertj:assertj-core:3.27.3',
            'commons-io:commons-io:2.18.0',
            'org.jbehave:jbehave-core:5.2.0'
    // Jupiter api and engine dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'

}
