defaultTasks 'clean', 'build'

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'eclipse'

version = '1.0-SNAPSHOT'
group = 'org.suggs.interviews.example'

wrapper {
    description = 'Generates gradlew scripts for NIX and win envs'
    gradleVersion = '7.3'
}

repositories {
    mavenCentral()
    mavenLocal()
}

idea.module {
    downloadSources = true
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.5'

    implementation 'org.slf4j:slf4j-log4j12:1.7.5',
            'log4j:log4j:1.2.17'

    testImplementation 'junit:junit:4.11'
}
